### ISSUE TITLE
Done button dosen't work in anki 23.10

### ISSUE THREAD

**Issue by Vilhelm-Ian** [fonol/anki-search-inside-add-card#373]
**Describe the bug**
When I press the done button for a pdf it gives me an error message. And dosen't load the next book in the que

**To Reproduce**
1. Install anki 23.10
2. Open first item in que
3. press done

**Environment (please complete the following information):**
 - OS: Linux, manjaro, wayland, QT6
 - Anki version 23.10

** ERROR log

AttributeError: 'DoneDialog' object has no attribute 'exec_'

I checked the code and Done Dialog has no Method exec_ . I tried added it to just so it won't crash 

def exec_(self)

just so it won't crash. But now when I press Done nothing happens

**Comment by Vilhelm-Ian** [comment]
https://github.com/fonol/anki-search-inside-add-card/commit/c3ec333f9d708c36862e6af5380dcc57eac6e013

this commit fixes it
